-- SQL statements to enrich course_blog_posts with descriptions
-- Generated: 2025-11-13T13:38:05.523116
-- Total courses: 24

INSERT INTO course_blog_posts (
    course_slug,
    course_code,
    title,
    website_description,
    content,
    published,
    created_at,
    updated_at
)
SELECT 
    c.slug,
    c.code,
    c.title_fr,
    'Ce cours traite des principaux contenus suivants : Calcul du revenu d''emploi, d''entreprise et de biens. Amortissement des biens corporels et incorporels. Calcul du gain en capital. Autres revenus et autres déductions. Calcul du revenu imposable des particuliers et plus particulièrement des pertes à reporter. Calcul de l''impôt à payer des particuliers.',
    'Content will be generated by AI', -- Placeholder content
    false, -- Not published yet
    NOW(),
    NOW()
FROM courses c
WHERE c.code = 'SCO3008' 
  AND c.institution = 'ESG-UQAM'
ON CONFLICT (course_slug) 
DO UPDATE SET
    website_description = EXCLUDED.website_description,
    updated_at = NOW();

INSERT INTO course_blog_posts (
    course_slug,
    course_code,
    title,
    website_description,
    content,
    published,
    created_at,
    updated_at
)
SELECT 
    c.slug,
    c.code,
    c.title_fr,
    'Ce cours traite des principaux contenus suivants : notions de débit et de crédit; nature des comptes; équation comptable fondamentale; cycle comptable; constatation des produits et des charges, rapprochement des charges et des produits, charges payées d''avance et à payer, produits constatés d''avance et à recevoir; immobilisations, amortissements, gains et pertes sur cession d''immobilisations; évaluation des stocks et coûts des marchandises vendues; comptabilité d''engagement et comptabilité de trésorerie; encaisse et placements temporaires; gestion et contrôle interne de la trésorerie; journaux et grands livres auxiliaires; traitement de la paie; établissement de la balance de vérification; régularisations de fin de période; préparation de l''état de la situation financière, de l''état des résultats et de l''état des variations des capitaux propres.',
    'Content will be generated by AI', -- Placeholder content
    false, -- Not published yet
    NOW(),
    NOW()
FROM courses c
WHERE c.code = 'SCO1240' 
  AND c.institution = 'ESG-UQAM'
ON CONFLICT (course_slug) 
DO UPDATE SET
    website_description = EXCLUDED.website_description,
    updated_at = NOW();

INSERT INTO course_blog_posts (
    course_slug,
    course_code,
    title,
    website_description,
    content,
    published,
    created_at,
    updated_at
)
SELECT 
    c.slug,
    c.code,
    c.title_fr,
    'Ce cours a pour objectif de permettre aux étudiants de prendre conscience de la complexité de l''environnement macroéconomique dans lequel les individus, les ménages et les entreprises évoluent, de connaître les mécanismes par lesquels les variables économiques influencent leurs décisions et enfin, de les familiariser avec les aspects théoriques, institutionnels et politiques de l''analyse macroéconomique appliquée à l''économie internationale. À la suite de ce cours, les étudiants devraient être en mesure de comprendre les principales théories qui permettent d''expliquer l''évolution de la production, de l''emploi, des prix, des taux d''intérêt et des taux de change et d''en percevoir les implications relativement au rôle des autorités de la politique économique. Les grandes questions de la macroéconomie: chômage, inflation, croissance et cycles économiques. Faits stylisés de l''économie canadienne: consommation des ménages, investissements des entreprises, dépenses gouvernementales et flux internationaux de biens et services et de capitaux. La monnaie, le crédit et la détermination des taux d''intérêt. Les marchés financiers internationaux. La balance des paiements, les régimes de taux de change et le financement du commerce extérieur. Conduite de la politique monétaire au Canada. Déficits budgétaires des gouvernements et évolution de la dette publique. Le chômage, l''inflation et les politiques de stabilisation dans le contexte de l''économie mondiale. La croissance économique au Canada et dans le monde. Les prévisions économiques et l''analyse conjoncturelle.',
    'Content will be generated by AI', -- Placeholder content
    false, -- Not published yet
    NOW(),
    NOW()
FROM courses c
WHERE c.code = 'ECO2400' 
  AND c.institution = 'ESG-UQAM'
ON CONFLICT (course_slug) 
DO UPDATE SET
    website_description = EXCLUDED.website_description,
    updated_at = NOW();

INSERT INTO course_blog_posts (
    course_slug,
    course_code,
    title,
    website_description,
    content,
    published,
    created_at,
    updated_at
)
SELECT 
    c.slug,
    c.code,
    c.title_fr,
    'Permettre à l''étudiant d''avoir un aperçu général des domaines internationaux de la finance, lui fournir la base des concepts fondamentaux de la gestion financière multinationale, le rendre capable de comprendre les problèmes financiers qui confrontent les entreprises multinationales et pouvoir ébaucher une solution, et enfin pouvoir analyser la situation financière d''une compagnie multinationale et être capable de faire des études préliminaires à la prise de décision. - Les principaux marchés financiers. - Les institutions financières étrangères. - La réglementation et les contrôles élastiques. - La gestion financière: utilisation et acquisition rationnelles des fonds. - Les systèmes fiscaux et les mouvements des capitaux entre divers pays. - Interprétation des états financiers établis à l''étranger par les branches et filiales. - Le contrôle financier des filiales succursales, et représentation à l''étranger.',
    'Content will be generated by AI', -- Placeholder content
    false, -- Not published yet
    NOW(),
    NOW()
FROM courses c
WHERE c.code = 'FIN5580' 
  AND c.institution = 'ESG-UQAM'
ON CONFLICT (course_slug) 
DO UPDATE SET
    website_description = EXCLUDED.website_description,
    updated_at = NOW();

INSERT INTO course_blog_posts (
    course_slug,
    course_code,
    title,
    website_description,
    content,
    published,
    created_at,
    updated_at
)
SELECT 
    c.slug,
    c.code,
    c.title_fr,
    'Ce cours a pour but d''analyser de façon rigoureuse le fonctionnement de ces nouveaux marchés financiers tant sur le plan théorique que pratique et de faire le lien entre ces marchés et ceux des titres traditionnels, surtout le marché obligataire. Plus spécifiquement, le cours vise à transmettre aux étudiants une compréhension solide de ces nouveaux instruments financiers, des principes d''évaluation qui leur sont applicables, des liens qui les unissent aux titres sous-jacents, et des stratégies de couverture, de spéculation, d''arbitrage et d''assurance de portefeuille qui les utilisent.',
    'Content will be generated by AI', -- Placeholder content
    false, -- Not published yet
    NOW(),
    NOW()
FROM courses c
WHERE c.code = 'FIN5550' 
  AND c.institution = 'ESG-UQAM'
ON CONFLICT (course_slug) 
DO UPDATE SET
    website_description = EXCLUDED.website_description,
    updated_at = NOW();

INSERT INTO course_blog_posts (
    course_slug,
    course_code,
    title,
    website_description,
    content,
    published,
    created_at,
    updated_at
)
SELECT 
    c.slug,
    c.code,
    c.title_fr,
    'Ce cours traite des principaux contenus suivants : Placements dans des coentreprises, des filiales et des entreprises associées. Contrôle et influence notable. Utilisation et impact de la valeur d''acquisition et de la méthode de mise en équivalence. Achat d''actions, achat d''actifs et méthode de l''acquisition. États financiers consolidés et secteurs opérationnels. Détermination des justes valeurs et du goodwill. Informations relatives aux parties liées. États financiers intermédiaires.',
    'Content will be generated by AI', -- Placeholder content
    false, -- Not published yet
    NOW(),
    NOW()
FROM courses c
WHERE c.code = 'SCO4240' 
  AND c.institution = 'ESG-UQAM'
ON CONFLICT (course_slug) 
DO UPDATE SET
    website_description = EXCLUDED.website_description,
    updated_at = NOW();

INSERT INTO course_blog_posts (
    course_slug,
    course_code,
    title,
    website_description,
    content,
    published,
    created_at,
    updated_at
)
SELECT 
    c.slug,
    c.code,
    c.title_fr,
    'Ce cours a pour objectif de permettre aux étudiants de prendre conscience de la complexité de l''environnement microéconomique dans lequel les individus, les ménages et les entreprises évoluent, de connaître les mécanismes par lesquels les variables économiques influencent leurs décisions et enfin, de les familiariser avec les aspects théoriques, institutionnels et politiques de l''analyse microéconomique appliquée à l''économie internationale. À la suite de ce cours, les étudiants devraient être en mesure de comprendre les principes de l''allocation des ressources dans les économies de marché et d''appliquer ces connaissances à la résolution de problèmes spécifiques à l''économie de l''entreprise, à l''économie industrielle et au commerce international.',
    'Content will be generated by AI', -- Placeholder content
    false, -- Not published yet
    NOW(),
    NOW()
FROM courses c
WHERE c.code = 'ECO1300' 
  AND c.institution = 'ESG-UQAM'
ON CONFLICT (course_slug) 
DO UPDATE SET
    website_description = EXCLUDED.website_description,
    updated_at = NOW();

INSERT INTO course_blog_posts (
    course_slug,
    course_code,
    title,
    website_description,
    content,
    published,
    created_at,
    updated_at
)
SELECT 
    c.slug,
    c.code,
    c.title_fr,
    'Principes et modèles d''analyse. Analyse de la rentabilité. Bénéfice économique et comptable. Analyse de l''industrie. Techniques de prévision. Analyse du risque. La nature et la mesure du risque. Principes de gestion de portefeuilles. Risque et prime de risque. Analyse technique, efficience des marchés financiers.',
    'Content will be generated by AI', -- Placeholder content
    false, -- Not published yet
    NOW(),
    NOW()
FROM courses c
WHERE c.code = 'FIN5521' 
  AND c.institution = 'ESG-UQAM'
ON CONFLICT (course_slug) 
DO UPDATE SET
    website_description = EXCLUDED.website_description,
    updated_at = NOW();

INSERT INTO course_blog_posts (
    course_slug,
    course_code,
    title,
    website_description,
    content,
    published,
    created_at,
    updated_at
)
SELECT 
    c.slug,
    c.code,
    c.title_fr,
    'Ce cours traite des principaux contenus suivants : Approfondissement des notions de gestion de coûts et de planification. D''une part, la comptabilité par activité, la production conjointe, les processus et les sections auxiliaires et, d''autre part, gérer le flux de trésorerie courant en développant des prévisions financières et des budgets, en enregistrant des informations sur les performances et en utilisant des outils de prise de décision à court terme. Outils de planification à court terme: Budgets des opérations. Budgets financiers. Gestion du processus de budgétisation (participation). Comptabilité de caisse. Éléments financiers pertinents. Budget flexible. Analyse d''écarts. Contrôles des dépenses discrétionnaires (budget base zéro, budget par activité, budgets spéciaux, financement des projets). Études de cas.',
    'Content will be generated by AI', -- Placeholder content
    false, -- Not published yet
    NOW(),
    NOW()
FROM courses c
WHERE c.code = 'SCO3001' 
  AND c.institution = 'ESG-UQAM'
ON CONFLICT (course_slug) 
DO UPDATE SET
    website_description = EXCLUDED.website_description,
    updated_at = NOW();

INSERT INTO course_blog_posts (
    course_slug,
    course_code,
    title,
    website_description,
    content,
    published,
    created_at,
    updated_at
)
SELECT 
    c.slug,
    c.code,
    c.title_fr,
    'Ce cours vise à compléter les connaissances acquises dans le cadre du cours FIN3500 - Gestion financière afin de mieux préparer l''étudiant aux défis de l''évolution permanente de l''industrie des services et des produits financiers pour qu''il puisse assumer plus de responsabilités ou exercer de nouvelles fonctions selon les standards professionnels. Le cours développe des connaissances indispensables en analyse financière selon l''approche comptable et du marché afin de pouvoir analyser l''information financière et de placements recueillie dans un contexte économique donné pour établir les rendements et tendances futures et pouvoir émettre des opinions éclairées aux clients tant du côté achat que du côté vente. Le cours présente des techniques d''évaluation des entreprises tant traditionnelles que l''entreprise de la nouvelle économie. Les notions d''éthique et de déontologie en finance seront présentées et analysées. La gouvernance de la firme ainsi que les fusions et acquisitions seront étudiées.',
    'Content will be generated by AI', -- Placeholder content
    false, -- Not published yet
    NOW(),
    NOW()
FROM courses c
WHERE c.code = 'FIN5570' 
  AND c.institution = 'ESG-UQAM'
ON CONFLICT (course_slug) 
DO UPDATE SET
    website_description = EXCLUDED.website_description,
    updated_at = NOW();

INSERT INTO course_blog_posts (
    course_slug,
    course_code,
    title,
    website_description,
    content,
    published,
    created_at,
    updated_at
)
SELECT 
    c.slug,
    c.code,
    c.title_fr,
    'Ce cours vise l''initiation de l''étudiant aux techniques permettant l''analyse et la prévision des fonds dont l''entreprise a besoin. On y aborde également les choix requis à court et à long terme pour l''allocation optimale des ressources d''une entreprise à ses différents secteurs d''activités. On y aborde aussi les notions d''allocation optimale de ressources primaires entre différentes possibilités d''investissement. On y traite des différentes sources de financement disponibles et des choix nécessaires en termes de coûts et de risques pour l''atteinte d''une politique financière optimale.',
    'Content will be generated by AI', -- Placeholder content
    false, -- Not published yet
    NOW(),
    NOW()
FROM courses c
WHERE c.code = 'FIN8415' 
  AND c.institution = 'ESG-UQAM'
ON CONFLICT (course_slug) 
DO UPDATE SET
    website_description = EXCLUDED.website_description,
    updated_at = NOW();

INSERT INTO course_blog_posts (
    course_slug,
    course_code,
    title,
    website_description,
    content,
    published,
    created_at,
    updated_at
)
SELECT 
    c.slug,
    c.code,
    c.title_fr,
    'Ce cours traite des principaux contenus suivants : Calcul du revenu imposable et de l''impôt sur le revenu à payer par une société. Avantages à l''actionnaire. Dividendes réputés. Ventes d''actions/d''actifs. Déduction pour gain en capital. Roulement de biens en faveur d''une société. Remaniement du capital-actions d''une société. Imposition des revenus étrangers. Taxes à la consommation (TPS et TVQ).',
    'Content will be generated by AI', -- Placeholder content
    false, -- Not published yet
    NOW(),
    NOW()
FROM courses c
WHERE c.code = 'SCO4008' 
  AND c.institution = 'ESG-UQAM'
ON CONFLICT (course_slug) 
DO UPDATE SET
    website_description = EXCLUDED.website_description,
    updated_at = NOW();

INSERT INTO course_blog_posts (
    course_slug,
    course_code,
    title,
    website_description,
    content,
    published,
    created_at,
    updated_at
)
SELECT 
    c.slug,
    c.code,
    c.title_fr,
    'Ce cours est offert hors programme (CRÉDITS NON COMPTABILISÉS). Cycle : 1 Type de cours : Magistral Nombre de crédits : 3 Discipline : Mathématiques Développer chez l''étudiant des connaissances, des habiletés et des outils de travail (de base) de type mathématique, statistique et informatique considérés comme nécessaires pour suivre avec intérêt et efficacité son programme d''études: également démystifier l''ordinateur et développer le goût des méthodes quantitatives. Introduction au chiffrier électronique. Utilisation de ce chiffrier pour le rappel du langage mathématique de base: expressions algébriques, expressions fonctionnelles, expressions ensemblestes et langage graphique, résolutions d''équations. Étude de la droite. Résolution graphique de systèmes d''équations et d''inéquations. Intérêts simple et composé. Analyse et interprétation de données mathématiques et statistiques de gestion.',
    'Content will be generated by AI', -- Placeholder content
    false, -- Not published yet
    NOW(),
    NOW()
FROM courses c
WHERE c.code = 'MAT1002' 
  AND c.institution = 'ESG-UQAM'
ON CONFLICT (course_slug) 
DO UPDATE SET
    website_description = EXCLUDED.website_description,
    updated_at = NOW();

INSERT INTO course_blog_posts (
    course_slug,
    course_code,
    title,
    website_description,
    content,
    published,
    created_at,
    updated_at
)
SELECT 
    c.slug,
    c.code,
    c.title_fr,
    'Ce cours vise à initier les étudiants à l''analyse et à la prévision financière, au financement de l''entreprise et à l''allocation des ressources financières. Techniques d''analyse et de prévision. Mathématiques financières. Choix des investissements et coût du capital. Fusion et acquisitions, gestion de l''encaisse. Gestion des comptes à recevoir. Sources de financement à court, moyen et long termes. Structure financière optimale. Politique de dividendes. Le cours sera suivi d''une période de trois heures d''exercices additionnelles. Ce cours implique une utilisation intensive des technologies d''information et de communication. L''étudiant doit prévoir l''accès à un micro-ordinateur et à Internet.',
    'Content will be generated by AI', -- Placeholder content
    false, -- Not published yet
    NOW(),
    NOW()
FROM courses c
WHERE c.code = 'FIN3500' 
  AND c.institution = 'ESG-UQAM'
ON CONFLICT (course_slug) 
DO UPDATE SET
    website_description = EXCLUDED.website_description,
    updated_at = NOW();

INSERT INTO course_blog_posts (
    course_slug,
    course_code,
    title,
    website_description,
    content,
    published,
    created_at,
    updated_at
)
SELECT 
    c.slug,
    c.code,
    c.title_fr,
    'Ce cours traite des principaux contenus suivants : Comptabilisation, évaluation et présentation aux états financiers des diverses opérations relatives aux passifs financiers (courants et non courants) et aux capitaux propres; aux provisions; aux actifs et passifs éventuels; aux engagements contractuels; et aux événements postérieurs à la date de clôture, y compris les fondements conceptuels sur lesquels reposent ces normes et pratiques. Traitement comptable des modifications de conventions comptables, des révisions d''estimations et des corrections d''erreurs. Calcul des liquidités générées par les principales activités de financement, d''investissement et opérationnelles et préparation d''un état des flux de trésorerie.',
    'Content will be generated by AI', -- Placeholder content
    false, -- Not published yet
    NOW(),
    NOW()
FROM courses c
WHERE c.code = 'SCO3240' 
  AND c.institution = 'ESG-UQAM'
ON CONFLICT (course_slug) 
DO UPDATE SET
    website_description = EXCLUDED.website_description,
    updated_at = NOW();

INSERT INTO course_blog_posts (
    course_slug,
    course_code,
    title,
    website_description,
    content,
    published,
    created_at,
    updated_at
)
SELECT 
    c.slug,
    c.code,
    c.title_fr,
    'Ce cours a pour objectif de permettre aux participants d''acquérir une connaissance et une compréhension de l''environnement économique dans lequel évoluent les entreprises. Il identifie et analyse les éléments et les concepts sur lesquels s''appuie la prise de décisions. Bien que l''analyse porte avant tout sur les économies canadienne et québécoise, elle tient aussi compte de l''ouverture de ces dernières au commerce international ainsi que de l''intégration mondiale des marchés financiers. Les thèmes suivants sont traités :
faits stylisés de l''économie canadienne: évolution de la consommation des ménages, des investissements des entreprises, des dépenses des gouvernements et des échanges internationaux de biens et services;
la balance des paiements, le taux de change et le financement du commerce extérieur;
les marchés financiers internationaux;
la monnaie, le crédit et la détermination des taux d''intérêt;
la conduite de la politique monétaire au Canada;
la production, l''inflation et les politiques de stabilisation;
les soldes budgétaires des gouvernements et la gestion de la dette publique;
la croissance économique;
les prévisions économiques et l''analyse conjoncturelle.',
    'Content will be generated by AI', -- Placeholder content
    false, -- Not published yet
    NOW(),
    NOW()
FROM courses c
WHERE c.code = 'ECO8402' 
  AND c.institution = 'ESG-UQAM'
ON CONFLICT (course_slug) 
DO UPDATE SET
    website_description = EXCLUDED.website_description,
    updated_at = NOW();

INSERT INTO course_blog_posts (
    course_slug,
    course_code,
    title,
    website_description,
    content,
    published,
    created_at,
    updated_at
)
SELECT 
    c.slug,
    c.code,
    c.title_fr,
    'Le cours a pour objet de présenter le rôle de l''information financière dans la prise de décisions économiques. Au terme de ce cours, l''étudiant sera capable de comprendre la nature de l''information financière préparée selon les Normes internationales d''information financière (IFRS) et les Normes comptables pour les entreprises à capital fermé (NCECF), de différencier les besoins des utilisateurs des rapports financiers, de sélectionner l''information pertinente selon le type de décisions économiques, d''évaluer les limites de l''information financière, de comprendre la terminologie utilisée, d''utiliser la littérature pour mieux saisir les problématiques financières et d''être conscient de l''importance de l''éthique dans l''exercice de la profession. Ce cours traite des principaux contenus suivants : - utilisateurs de l''information financière. Rôle et intervention des experts-comptables; - concepts fondamentaux des différents domaines liés aux sciences comptables; - nature et utilité de l''information financière; - analyse des opérations sur la base de l''équation comptable; - information financière portant sur les résultats, les flux de trésorerie, les ressources économiques et les sources de capitaux.',
    'Content will be generated by AI', -- Placeholder content
    false, -- Not published yet
    NOW(),
    NOW()
FROM courses c
WHERE c.code = 'SCO1250' 
  AND c.institution = 'ESG-UQAM'
ON CONFLICT (course_slug) 
DO UPDATE SET
    website_description = EXCLUDED.website_description,
    updated_at = NOW();

INSERT INTO course_blog_posts (
    course_slug,
    course_code,
    title,
    website_description,
    content,
    published,
    created_at,
    updated_at
)
SELECT 
    c.slug,
    c.code,
    c.title_fr,
    'Ce cours traite des principaux contenus suivants : Fonctions de la comptabilité de management. Les modes de fabrication sur commande et uniforme. Les marges et la prise de décision. L''analyse coûts-volumes-bénéfices et les éléments pertinents à la prise de décision. Études de cas.',
    'Content will be generated by AI', -- Placeholder content
    false, -- Not published yet
    NOW(),
    NOW()
FROM courses c
WHERE c.code = 'SCO2001' 
  AND c.institution = 'ESG-UQAM'
ON CONFLICT (course_slug) 
DO UPDATE SET
    website_description = EXCLUDED.website_description,
    updated_at = NOW();

INSERT INTO course_blog_posts (
    course_slug,
    course_code,
    title,
    website_description,
    content,
    published,
    created_at,
    updated_at
)
SELECT 
    c.slug,
    c.code,
    c.title_fr,
    'Taux d''intérêt et équilibre des marchés financiers, échéances et structure des taux d''intérêt. Durée du crédit et échéance: protection contre le risque de fluctuations des taux d''intérêts. Clauses de rachat. Analyse du risque d''insolvabilité. Impôts et autres influences gouvernementales sur l''allocation des ressources financières. Analyse des titres convertibles. Gestion de portefeuilles d''obligations; stratégies de gestion. Caractéristiques et évaluation des options.',
    'Content will be generated by AI', -- Placeholder content
    false, -- Not published yet
    NOW(),
    NOW()
FROM courses c
WHERE c.code = 'FIN5523' 
  AND c.institution = 'ESG-UQAM'
ON CONFLICT (course_slug) 
DO UPDATE SET
    website_description = EXCLUDED.website_description,
    updated_at = NOW();

INSERT INTO course_blog_posts (
    course_slug,
    course_code,
    title,
    website_description,
    content,
    published,
    created_at,
    updated_at
)
SELECT 
    c.slug,
    c.code,
    c.title_fr,
    'Ce cours a pour objectif de permettre à l''étudiant de se familiariser avec les techniques décisionnelles et d''optimisation de la recherche opérationnelle et plus spécifiquement de rendre l''étudiant apte à percevoir dans quel état se situe un problème donné, à identifier ses variables, à analyser et optimiser le phénomène à étudier et enfin d''être capable d''étudier et de comprendre les techniques connexes à celles présentées en séance. - Nature de la recherche opérationnelle - Cycle de décision - Modèle de décision - Décision en état d''ignorance - Programmation linéaire - Solution graphique - Solution algébrique - Méthode simplexe - Méthode de l''affectation - Affectation cyclique - Méthode du transport - Programmation dynamique - Décision en état de risque - Probabilités bayésiennes - Valeur de l''information - Théorie des files d''attente - Canal simple - Canaux multiples - Canal simple tronqué - Troncation absolue - Méthode de simulation Monte-Carlo - Réseau - Distribution Bêta - Variations des coûts et des temps - Décision en état de conflit - Théorie des jeux',
    'Content will be generated by AI', -- Placeholder content
    false, -- Not published yet
    NOW(),
    NOW()
FROM courses c
WHERE c.code = 'AOT3220' 
  AND c.institution = 'ESG-UQAM'
ON CONFLICT (course_slug) 
DO UPDATE SET
    website_description = EXCLUDED.website_description,
    updated_at = NOW();

INSERT INTO course_blog_posts (
    course_slug,
    course_code,
    title,
    website_description,
    content,
    published,
    created_at,
    updated_at
)
SELECT 
    c.slug,
    c.code,
    c.title_fr,
    'La gestion des opérations (GO) joue un rôle fondamental dans le fonctionnement des organisations. Elle permet de concevoir, de gérer et d''améliorer l''ensemble des processus des organisations (et de leurs réseaux) afin de créer de la valeur pour les clients. La GO est une discipline concrète qui permet aux organisations de s''adapter aux besoins changeants d''un contexte économique turbulent et d''atteindre leurs objectifs. L''objectif principal de ce cours est d''amener les étudiants à comprendre les principaux concepts et méthodes en GO. Les thèmes suivants seront couverts : La GO dans les organisations et ses interrelations avec les autres disciplines L''impact de la GO sur la compétitivité, la productivité et l''agilité des organisations Les rôles et les responsabilités en GO L''analyse d''un système opérationnel et de ses processus La planification de la demande et la gestion des ressources La planification des opérations et la gestion logistique L''utilisation des technologies en GO L''amélioration de la performance des processus',
    'Content will be generated by AI', -- Placeholder content
    false, -- Not published yet
    NOW(),
    NOW()
FROM courses c
WHERE c.code = 'AOT4200' 
  AND c.institution = 'ESG-UQAM'
ON CONFLICT (course_slug) 
DO UPDATE SET
    website_description = EXCLUDED.website_description,
    updated_at = NOW();

INSERT INTO course_blog_posts (
    course_slug,
    course_code,
    title,
    website_description,
    content,
    published,
    created_at,
    updated_at
)
SELECT 
    c.slug,
    c.code,
    c.title_fr,
    'La connaissance et l''aptitude à utiliser les principes de la comptabilité nécessaires à l''administration d''une industrie. Notions élémentaires de comptabilité industrielle. Planification et contrôle budgétaire dans l''entreprise industrielle. Le prix de revient normal et standard. Le comportement des coûts: interaction coûts-volume-bénéfice. Les coûts proportionnels. Les coûts pertinents et la prise de décision à court terme: utilisation des ressources existantes. La rentabilité des investissements et la prise de décision à long terme. L''étudiant pourra suivre, sur une base facultative, des laboratoires consacrés à l''application des concepts présentés dans les cours.',
    'Content will be generated by AI', -- Placeholder content
    false, -- Not published yet
    NOW(),
    NOW()
FROM courses c
WHERE c.code = 'SCO2000' 
  AND c.institution = 'ESG-UQAM'
ON CONFLICT (course_slug) 
DO UPDATE SET
    website_description = EXCLUDED.website_description,
    updated_at = NOW();

INSERT INTO course_blog_posts (
    course_slug,
    course_code,
    title,
    website_description,
    content,
    published,
    created_at,
    updated_at
)
SELECT 
    c.slug,
    c.code,
    c.title_fr,
    'Introduction au calcul différentiel et intégral (du point de vue des applications).
Concept de fonction.
Rappels concernant les exposants.
Fonctions exponentielles, logarithmiques et puissances.
Fonctions trigonométriques.
Suites numériques.
Limites et continuité de fonctions.
Dérivée d''une fonction.
Dérivées d''ordre supérieur.
Applications de la dérivée.',
    'Content will be generated by AI', -- Placeholder content
    false, -- Not published yet
    NOW(),
    NOW()
FROM courses c
WHERE c.code = 'MAT0343' 
  AND c.institution = 'ESG-UQAM'
ON CONFLICT (course_slug) 
DO UPDATE SET
    website_description = EXCLUDED.website_description,
    updated_at = NOW();

INSERT INTO course_blog_posts (
    course_slug,
    course_code,
    title,
    website_description,
    content,
    published,
    created_at,
    updated_at
)
SELECT 
    c.slug,
    c.code,
    c.title_fr,
    'Ce cours traite des principaux contenus suivants : Stocks. Créances. Placements comme actifs financiers. État du résultat net et du résultat global. Activités abandonnées. Immobilisations corporelles. Actifs incorporels. Échanges d''actifs. Aide et subvention publiques. Constatation des produits.',
    'Content will be generated by AI', -- Placeholder content
    false, -- Not published yet
    NOW(),
    NOW()
FROM courses c
WHERE c.code = 'SCO2240' 
  AND c.institution = 'ESG-UQAM'
ON CONFLICT (course_slug) 
DO UPDATE SET
    website_description = EXCLUDED.website_description,
    updated_at = NOW();

