#!/usr/bin/env python3
"""
Generate a CSV file ready for Supabase upload.
Transforms the domain-based CSV into course-level records.
"""

import csv
import sys

def parse_percentage(value):
    if not value or value.strip().upper() == 'N/A':
        return None
    try:
        return float(value.strip().replace('%', '')) / 100.0
    except:
        return None

def parse_rating(value):
    if not value or value.strip().upper() == 'N/A':
        return None
    try:
        return float(value.strip())
    except:
        return None

def parse_num_ratings(value):
    if not value:
        return 0
    try:
        cleaned = value.strip().lower().replace('ratings', '').replace('rating', '').strip()
        return int(cleaned) if cleaned else 0
    except:
        return 0

def normalize_domain(domain):
    if not domain:
        return domain
    domain = domain.strip().lower()
    mapping = {
        'comptabilité': 'Comptabilité',
        'comptabilite': 'Comptabilité',
        'finance': 'Finance',
        'économie': 'Économie',
        'economie': 'Économie',
        'gestion': 'Gestion des opérations',  # CSV has "gestion" but DB has "Gestion des opérations"
        'mathématiques': 'Mathématiques',
        'mathematiques': 'Mathématiques',
    }
    return mapping.get(domain, domain.capitalize())

courses_by_domain = {
    ('Finance', 'ESG-UQAM'): ['fin3500', 'fin5521', 'fin5523', 'fin5550', 'fin5570', 'fin5580', 'fin8415'],
    ('Comptabilité', 'ESG-UQAM'): ['sco1240', 'sco1250', 'sco2000', 'sco2001', 'sco2240', 'sco3001', 'sco3008', 'sco3240', 'sco4008', 'sco4240'],
    ('Économie', 'ESG-UQAM'): ['eco1300', 'eco2400', 'eco8402'],
    ('Gestion des opérations', 'ESG-UQAM'): ['aot3220', 'aot4200'],
    ('Mathématiques', 'ESG-UQAM'): ['mat0343', 'mat1002'],
}

def main():
    if len(sys.argv) < 2:
        print("Usage: python generate_upload_csv.py <input_csv> [output_csv]")
        print("Example: python generate_upload_csv.py RMP_ESG-UQAM.csv upload_ready.csv")
        sys.exit(1)
    
    input_csv = sys.argv[1]
    output_csv = sys.argv[2] if len(sys.argv) > 2 else 'professor_ratings_upload.csv'
    
    print(f"Reading {input_csv}...")
    
    records = []
    
    with open(input_csv, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        
        for row in reader:
            num_ratings = parse_num_ratings(row.get('number of ratings', ''))
            if num_ratings == 0:
                continue
            
            prof_name = row.get('full name', '').strip()
            domain = normalize_domain(row.get('domaine', ''))
            institution = row.get('institution', '').strip()
            
            if not prof_name or not domain or not institution:
                continue
            
            key = (domain, institution)
            courses = courses_by_domain.get(key, [])
            
            if not courses:
                continue
            
            overall_rating = parse_rating(row.get('quality rating', ''))
            difficulty = parse_rating(row.get('level of difficulty score', ''))
            would_take_again = parse_percentage(row.get('would take again score', ''))
            
            # Create one record per course
            for course_slug in courses:
                record = {
                    'course_slug': course_slug,
                    'professor_name': prof_name,
                    'professor_rmp_id': '',  # Empty string, will be NULL in DB
                    'overall_rating': str(overall_rating) if overall_rating is not None else '',
                    'difficulty_rating': str(difficulty) if difficulty is not None else '',
                    'would_take_again': str(would_take_again) if would_take_again is not None else '',
                    'total_ratings': str(num_ratings),
                    'best_for': '',
                    'worst_for': '',
                    'last_updated': '',  # Will use NOW() default
                }
                records.append(record)
    
    print(f"Generated {len(records)} records")
    print(f"Writing to {output_csv}...")
    
    # Write CSV
    fieldnames = ['course_slug', 'professor_name', 'professor_rmp_id', 'overall_rating', 
                  'difficulty_rating', 'would_take_again', 'total_ratings', 'best_for', 
                  'worst_for', 'last_updated']
    
    with open(output_csv, 'w', encoding='utf-8', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(records)
    
    print(f"CSV ready for upload: {output_csv}")
    print(f"\nNote: UUIDs (id), created_at, and updated_at will be auto-generated by Supabase")
    print(f"Empty strings will be treated as NULL in Supabase")

if __name__ == '__main__':
    main()

